[package]
name = "tcp_pty"
version = "0.1.0"
edition = "2021"

[dependencies]
exec = "0.3.1"
futures = "0.3.21"
nix = "0.24.1"
tokio = { version = "1.18.2", features = ["rt", "macros", "net", "io-util"] }
